Allows non admins to use the block
humanmade/google-map-gutenberg-block pull request #4
Opened 2018-12-18 16:36 UTC by roborourke

Bit hacky but this is an improvement in terms of allowing non admins to use the block.

2018-12-18 17:43 UTC, joemcgill requested changes
A couple notes, otherwise looks good.

2018-12-18 17:43 UTC, joemcgill commented on embed-gutenberg-block-google-maps.php
> +			get_google_api_key(),
esc_attr

2018-12-18 17:43 UTC, joemcgill commented on src/js/EditorBlock.js
> +		console.log( this.state, this.state.apiKey === '' )
Leftover from debugging?

2018-12-19 16:13 UTC, roborourke commented on src/js/EditorBlock.js
> +		console.log( this.state, this.state.apiKey === '' )
whoops!

2018-12-19 16:13 UTC, roborourke commented on embed-gutenberg-block-google-maps.php
> +			get_google_api_key(),
classic

2018-12-19 16:14 UTC, roborourke commented on embed-gutenberg-block-google-maps.php
> +			get_google_api_key(),
```suggestion
			esc_attr( get_google_api_key() ),
```

2018-12-19 16:15 UTC, roborourke commented on src/js/EditorBlock.js
> +		console.log( this.state, this.state.apiKey === '' )
```suggestion
```

2018-12-19 16:15 UTC, merged